image: gbraad/docugen:latest

pages:
  script:
  - pandoc -w revealjs --template template/reveal-slides-template.html --no-highlight -o index.html ./md/cd.md
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
